# .goreleaser.yml
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
builds:
  - binary: standardfile
    ldflags:
      - -w -X main.BuildTime={{ .Date }} -X main.Version={{ .Version }}
    goos:
      - windows
      - darwin
    goarch:
      - 386
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
    env:
      - CGO_ENABLED=0
    hooks:
      post: ./build-linux-cgo.sh
release:
  github:
    owner: tectiv3
    name: standardfile
archive:
  name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}{{ .Arm }}{{ end }}"
  replacements:
    amd64: 64-bit
    386: 32-bit
    darwin: macos